module.exports.ErrorMessage = Object.freeze({
  PHONE_EMPTY: "Valid mobile number is require",
  NAME_EMPTY: "name is mandatory for registration in string formate",
  INVALID_EMAIL: "please check your email_id invalid.",
  INVALID_TOKEN: "Unauthorized user.",
  INTERNAL_ERROR: "Internal Server Error.",
  INVALID_CREDENTIAL: "Invalid credentials.",
  SOMETHING_WRONG: "Something went wrong!",
  ALREADY_EXIST_EMAIL: "Already exists this emailId.",
  NO_TOKEN: "Please provide token.",
  NOT_REGISTERED: "Provided mobileNumber is not registered.",
  RESET_PASSWORD_EXPIRED: "Your Token has expired.",
  INVALID_MOBILE: "This mobile number is not valid.",
  NOT_FOUND: "Requested data not found.",
  USER_NOT_FOUND: "This user does not exist.",
  UPDATE_NOT: "Unexpected error during update, please try again.",
  MOBILE_EXIST: "This mobile number already registered.",
  USERNAME_EXIST: "This user name already exists.",
  USER_ID: "A valid User Id is required.",
  
  FIELD_REQUIRED: "Fields are required.",
  INCORRECT_JWT: "Invalid JWT token.",
  INVALID_OTP: "Invalid OTP",
  OTP_EXPIRED: "OTP has expired, please try resend OTP.",
  UPLOAD_DOCUMENT: "Your otp has been verified, Please verified your document.",
  CONTACT_NOT_FOUND: "ContactUs Form Data not found.",
});
module.exports.SuccessMessage = Object.freeze({
  SIGNUP_SUCCESSFULLY: "Thanks, You have successfully signed up.",
  LOGIN_SUCCESS: "Login Successfully!",
  LOGOUT_SUCCESS: "Your account has been logout successfully.",
  USER_CREATE: "User has been created successfully.",
  CUSTOMER_VERIFY: "Customer verified successfully",
  CUSTOMER_ALREADY_VERIFY: "Otp already verified.",
 
  RESET_SUCCESS: "Your password has been successfully changed.",
  PRODUCT_LIST_FETCH: "Successfully fetched product list.",
  UPLOAD_DOCUMENT: "Your document has been upload successfully.",
  DOCUMENT_ALREADY_UPLOAD: "Document already upload.",
  DOCUMENT_NOT_VERIFIED: "Document not verified.",
  USER_LIST_FETCH: "Successfully fetched user list.",
  AUTHORIZATION: "This User is Authorized.",
  ACCOUNT_CREATION: "Your account has been created successfully.",
 
  OTP_SEND: "OTP sent successfully.",
  VERIFY_OTP: "OTP verified successfully.",
  PIN_SET: "Your Pin has been set successfully.",
  PASSWORD_UPDATE: "Your password has been updated successfully.",
  DATA_SAVED: "Data is saved successfully.",
  DETAIL_GET: "Details have been fetched successfully.",
  DATA_FOUND: "Requested data found",
  PROFILE_DETAILS: "Your profile details has been updated successfully.",
  STATUS_UPDATED: "Your Status has been changed successfully.",
  UPDATE_SUCCESS: "Successfully updated.",
  BLOCK_SUCCESS: "Successfully blocked.",
  UNBLOCK_SUCCESS: "Successfully activated.",
  DELETE_SUCCESS: "Successfully deleted.",
  SMS_SEND: "The SMS has been send to the buddies successfully.",
  CATEGORY_ADD: "Category has been added successfully.",
  MESSAGE_ADD: "The message has been added successfully.",
  PRODUCT_ADD: "Product has been added successfully.",
  TRANSACTION_DONE: "Transaction done successfully.",
  KYC_REJECT: "Kyc is rejected successfully.",
  KYC_ACCEPT: "Kyc is accepted successfully.",
  REJECT_BOOKING: "Cancel booking successfully.",
  FAVOURITE_SUCCESS: "Item has been favourited successfully.",
  UNFAVOURITE_SUCCESS: "Item has been unfavourited successfully.",
  INCREMENTED: "Successfully incremented by value 1.",
  DECREMENTED: "Successfully decremented by value 1.",
  CART_SAVED: "Added successfully.",
  CART_ALREADY: " Already exist.",
  BROADCAST_SUCCESS: "Send Broadcast Message Successfully",
  LOCATION_UPDATE_SUCCESS: "Location update Successfully.",
  ONLINE_UPDATE_SUCCESS: "User online status update Successfully.",
  CONTACT_US_FORM_DELETE: "Your ContactUs Form Delete Successfully.",
});
